### ISSUE TITLE
Indentation error ra_generate_fiber.py

### ISSUE THREAD

**Issue by patymardi** [KIT-IBT/AugmentA#1]
In line 1274 when creating the Bachmann Bundle when args.mesh_type= bilayer, the pipeline stops after creating RA_endo_with_fiber.vtk, this is because the next section runs only if args.mesh_type =="vol". I just indented once all the code so that with either bilayer or vol it goes down to the create_bridges.py
        # Bachmann-Bundle
1274        if args.mesh_type =="vol": 
        # from this line till the end should have 1 indentation more, so from 1 to two tabs

**Comment by axel-loewe** [comment]
Is this still open @patymardi?

**Comment by patymardi** [comment]
It is fixed @axel-loewe
