### ISSUE TITLE
Error with import PyMesh module 

### ISSUE THREAD

**Issue by patymardi** [KIT-IBT/AugmentA#2]
ModuleNotFoundError: No module named 'pymesh' in ra_main.py
When: Error appears when calling main.py 
Solution: PyMesh module has to be downloaded from source.
System: macOS Mojave 10.14.6

**Comment by axel-loewe** [comment]
If you just posted this issue to keep track for yourself, that's fine.

If you are hoping for some help, we would need more information. What's the error? How and where was it installed (IBT system or other system, operating system, using pip and requirements.txt or using pip directly? )

**Comment by patymardi** [comment]
Thanks, Axel. At the moment I am working to find a way to solve this issue with my IBT computer. I could expand the description so that everyone can understand the error. This issue might affect every user running the pipeline. At least, I had this trouble with both my IBT and my personal computer, and the solutions are different in both cases.

**Comment by patymardi** [comment]
For installing PyMesh there are some [system dependencies ](https://pymesh.readthedocs.io/en/latest/installation.html#building-pymesh) needed to build it. I already tried to install them manually but I am still facing troubles, as more and more dependencies are being required (Marie is helping as well). Would it be then possible @axel-loewe  to have the PyMesh dependencies installed on my IBT computer with an admin profile? E.g. using MacPorts. Thank you

**Comment by axel-loewe** [comment]
Dependencies should be installed centrally.
The python dependencies were all already installed. The other ones mostly as well. 

If you find another one that's missing, I can install it but to me pymesh seems to work well on the IBT systems. Tests are passing and only throw a couple of deprecation warnings:
```
al128lokal@ibt31:~$ python -c "import pymesh; pymesh.test()"
Running unit tests for pymesh
NumPy version 1.21.3
NumPy relaxed strides checking option: True
NumPy is installed in /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy
Python version 3.7.12 (default, Nov 11 2021, 17:34:58) [Clang 10.0.1 (clang-1001.0.46.4)]
nose version 1.3.7
......................................................................./opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/fft/__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/sparse/sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
....../Volumes/bordeaux/IBT10.10/thirdparty/src/PyMesh/python/pymesh/misc/quaternion.py:16: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self.__quat = np.array(quat, dtype=np.float)
.............................Warning: Complex edge loop detected!  Vertex 0 has valance 3

Warning: Complex edge loop detected!  Vertex 0 has valance 3

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:573: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
.............................................................S......S
----------------------------------------------------------------------
Ran 175 tests in 4.628s

OK (SKIP=2)
```

**Comment by axel-loewe** [comment]
Considering the error you reported above, which python interpreter are you using? Are you sure your `PYTHONPATH` includes /Volumes/bordeaux/IBT10.10/thirdparty/src/PyMesh?
This is included automatically via the central .zshrc when running python from the zsh terminal on IBT systems

**Comment by patymardi** [comment]
I am using Python 3.7 from IBT. The PyMesh module is actually located at:
`/Volumes/bordeaux/IBT10.10/thirdparty/src/PyMesh/build/lib.macosx-10.14-x86_64-3.7`
There is another module with the same name `PyMesh`, so always double check that there is no other pymesh already installed. It is working now.
