### ISSUE TITLE
Sklearn and carputils not in the requirement file

### ISSUE THREAD

**Issue by aashildte** [KIT-IBT/AugmentA#4]
Hi Luca,

Thanks for publishing this code :)

I was trying to install this code, and in the installation process I ran into the following issues:

> 
> `
>   File "AugmentA-main/standalones/open_orifices_with_curvature.py", line 37, in <module>
>     from sklearn.cluster import KMeans
> ModuleNotFoundError: No module named 'sklearn'
> `

and next

> `
>   File "AugmentA-main/Atrial_LDRBM/LDRBM/Fiber_LA/la_main.py", line 33, in <module>
>     from carputils import settings
> ModuleNotFoundError: No module named 'carputils'
> `

I installed those two independently and it works now, so no current issue for me. However, I was thinking that you might want to add these dependencies in your requirement file? Maybe?

**Comment by aashildte** [comment]
- and meshtool is another one :)

**Comment by axel-loewe** [comment]
Thanks for the feedback! We've extended the documentation on dependencies and added scikit-learn to the `requirements` file: 
https://github.com/KIT-IBT/AugmentA/commit/9a1ef483d1411f24aa58a36a6e64f0feef439ecb

**Comment by aashildte** [comment]
@axel-loewe nice, thanks!

I tried reinstalling it today, and line 5 has a minor error:

> h5py=3.7.0``

should probably be

> h5py~=3.7.0

otherwise everything seems to work :)

**Comment by axel-loewe** [comment]
> @axel-loewe nice, thanks!
> 
> I tried reinstalling it today, and line 5 has a minor error:
> 
> > h5py=3.7.0``
> 
> should probably be
> 
> > h5py~=3.7.0
> 
> otherwise everything seems to work :)

Thanks, fixed!
