### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by aashildte** [KIT-IBT/AugmentA#5]
Hi again :) Not trying to be difficult here - hoping this is indeed useful feedback for you.

I tried to run the four examples, and none of them ran out of the box. For the first and second example, I get the following error message:

> `OSError: /home/aashild/Documents/Software/AugmentA-main/AugmentA/mesh//LA_clean.curv.dat not found.`

so that's probably a missing file. For the third example, I get

> `  File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/standalones/open_orifices_manually.py", line 310, in point_array_mapper
>     if isinstance(data[0], collections.Sized):
> AttributeError: module 'collections' has no attribute 'Sized'
> `

and here I suspect that we have different versions of Python. May I ask which version you're running? Mine is 3.10.6. I actually don't know is this is a quick-fix for you or if it is easier if I run a different Python version.

For the forth example, I get

`  File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/pipeline.py", line 202, in AugmentA
    elif apex_id is not None:
UnboundLocalError: local variable 'apex_id' referenced before assignment
`
and again I wonder if this is a Python version thing: it tells me that apex_id isn't defined, but maybe there is a version of Python where all undefined variables are None? This is definitely easy to fix though, e.g. by initially declaring apex_id to be None.

**Comment by patymardi** [comment]
Changes were made and incorporated #7
