### ISSUE TITLE
Remeshing option doesn't work

### ISSUE THREAD

**Issue by aashildte** [KIT-IBT/AugmentA#6]
Hi again :) Another detail, nothing important or urgent about this either.

I tried to change the mesh resolution using the command 

> `--target_mesh_resolution`

and at first I was confused, as nothing changed. So maybe a suggestion here would be to e.g. put in a hint in the help text that also

> `--resample_input`

needs to be set to 1 for this to work. Next, I did set this to 1. As, with my meshes, I have None as my apex_id this failed at 

> `  File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/standalones/resample_surf_mesh.py", line 103, in resample_surf_mesh
>     if apex_id>-1:
> TypeError: '>' not supported between instances of 'NoneType' and 'int' `

so this can e.g. be solved by changing this line to

> `if apex_id is not None and apex_id>-1:`

so that worked fine (providing it should be None and not -1, and that the mistake is that it should be -1 and not None? ref. previous issue). Next, though, I get this error message:

> `Traceback (most recent call last):
>   File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/main.py", line 121, in <module>
>     run()
>   File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/main.py", line 118, in run
>     AugmentA(args)
>   File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/pipeline.py", line 179, in AugmentA
>     resample_surf_mesh('{}'.format(meshname), target_mesh_resolution=0.4, find_apex_with_curv=1, scale=args.scale, apex_id=apex_id)
>   File "/home/aashild/Documents/Software/AugmentA-main/AugmentA/standalones/resample_surf_mesh.py", line 204, in resample_surf_mesh
>     ms.remeshing_isotropic_explicit_remeshing(iterations=5, targetlen=loc_tgt_edge_length)
>   File "/home/aashild/.local/lib/python3.10/site-packages/pymeshlab/__init__.py", line 41, in foo
>     res_dict = self.apply_filter(name, **kwargs)
> pymeshlab.pmeshlab.PyMeshLabException: Parameter targetlen: must be a pymeshlab.Percentage object or apymeshlab.AbsoluteValue object. Other type values are not accepted.`

and this one I'm not so sure how to solve.

On a side note, these are some warnings I get when running this option (not so sure how important they are):

> `Warning: Deprecated Filter Warning: You should use 'compute_selection_by_self_intersections_per_face' instead of 'select_self_intersecting_faces'. See https://pymeshlab.readthedocs.io/en/latest/index.html#filters-renaming
> Warning: Deprecated Filter Warning: You should use 'get_geometric_measures' instead of 'compute_geometric_measures'. See https://pymeshlab.readthedocs.io/en/latest/index.html#filters-renaming
> Warning: Deprecated Filter Warning: You should use 'meshing_isotropic_explicit_remeshing' instead of 'remeshing_isotropic_explicit_remeshing'. See https://pymeshlab.readthedocs.io/en/latest/index.html#filters-renaming`

-- Åshild

**Comment by axel-loewe** [comment]
Thanks for the suggestions.
They were implemented in https://github.com/KIT-IBT/AugmentA/commit/faeecc6204307279bd6517273c701de60ddc2400

Regarding the error, it seems that pymeshlab now explicitly distinguishes between absolute values and percentages: https://pymeshlab.readthedocs.io/en/latest/classes/absolute_value.html
